export const BOMB_TIMER = 5000;
export const PLAYER_INVINCIBLE_TIME = 5000;

export const PLAYER_SETTINGS = {
  SPAWN_TIME: 5000,
  BASE_SPEED: 100,
  BASE_EXPLOSION_MULTIPLIER: 2,
  BASE_SPEED_MULTIPLIER: 0,
  MAX_SPEED_MULTIPLIER: 3,
  MAX_EXPLOSION_MULTIPLIER: 8,
  SPEED_BOOSTER: 20
};

export const ENEMY_SETTINGS = {
  IDLE_SPEED: 400,
  MAX_SPEED: 900
};
